vaadin.launch-browser=false

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/movies}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:movies}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:movies}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
